### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by tylerprete**

### CODE REVIEW

**Comment by tylerprete** [comment]
@Nikolaj-K Adding some logos for Altif. Does this fit the structure you had in mind?

**Comment by Nikolaj-K** [comment]
@tylerprete Hi Tyler, thanks for adding them. 
I mostly just initialized the repo because someone on the discord asked for these kind of resources, I don't directly planned to work on it and so you don't really need to ask. And you can also do it just on the forked repo, not here.
So indeed now that I see you got a whole lot of logos, it might be a good idea to restructure it accordingly and keep it straight forward to find it in categories - e.g. make a logo folder and put them in subcategories. I can do such a thing, if you think it would help, or make suggestions and structure it yourself.

**Comment by Nikolaj-K** [comment]
@tylerprete You pushed the branch to the Constellation-Labs one, but if you did the PR request on github, it probably was targeting another default. 
I had a related problem on the weekend, where I'm writing an academic paper that someone I know wants to use in a whitepaper, so their forked my stuff, and when I want to "send them an update", github is simply to stupid to smoothly allow pushing "in the wrong direction" upstream/downstream.
Yeah I would have made a `logo` folder and make your folders subfolders of that one. I'd also denote the `web-formats` folders as `raster-formats`, but I don't know all that much about formats, so mayb web-formats is standard.

**Comment by tylerprete** [comment]
Ah I see. Interesting that github defaulted to that. I guess this repo is the fork, so the PR defaults to requesting back to the origin, ala the standard fork/PR model. I actually went ahead and pushed a logos folder to master. I don't know what's standard with regards to naming -- just wanted to get the images up there. Feel free to suggest any changes in a PR if you want, the current ones were picked fairly arbitrarily.  Closing this PR.

**Comment by Nikolaj-K** [comment]
@tylerprete I think I own the visual-identity and awesome-constellation one, so I might just curate them without bothering people with PR's on prettifications - unless you want to be informed of that changes, then tell me :P

As an aside, I've also pretty much refactored the [wiki](https://github.com/Constellation-Labs/constellation/wiki) on the /constellation repo and tried to make a red thread on what content should be in the [/docs](https://github.com/Constellation-Labs/constellation/tree/dev/docs) vs. what should be on the wiki. 
I hope that somewhat makes sense/is clear/is in line with what you guys had in mind. I started reviewing the papers and where the comparsion and motivation sections, but I'm not sure where you are with that - might be that you're well too busy for docu/wiki right now, although I saw the issues tab on the project github site (the "scrum" type one).

**Comment by tylerprete** [comment]
As for prettifications -- go for it. 

I haven't put a ton of thought into the docs vs wiki issue, tbh. I'll have to look into it more. We can talk more on discord, etc, if you want

**Pull request closed without merging**
